import org.opencv.core.Core;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {

	static {
		System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
	}

	public static void main(String[] args) {

	}
}
